
services:
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017 
    environment:
     MONGO_INITD_ROOT_USERNAME: development
     MONGO_INITD_ROOT_PASSWORD: testgo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:  
      ME_CONFIG_MONGO_INITD_ROOT_USERNAME: development
      ME_CONFIG_MONGO_INITD_ROOT_PASSWORD: testgo
      ME_CONFIG_MONGO_URL: mongodb://development:testgo@mongo:27017/